@startuml

class leaf{
   +operation();
}

class component
{
    +operation();
    +add();
    +remove();
    +getChild();
}

class composite{
    +operation();
    +add();
    +remove();
    +getChild();
}

class composite
note top of composite
operation(){
    for(Component component:children){
        component.operation()
     }
 }
end note
leaf --|> component
composite --|> component
composite o--> component :children

@enduml