@startuml

class Context{
    -Strategy strategy;
    +Algorithm();
}

interface Strategy{
    +Algorithm();
}

ConcreteStrategyA --|> Strategy
ConcreteStrategyB --|> Strategy
Context o--> Strategy : strategy

@enduml