@startuml

class Target{
    +request();
}

class Adaptor{
    +request();
}

class Adaptee{
    +specificRequest();
}

Adaptor ..|> Target
Adaptor --> Adaptee
client --> Adaptor: 新
client --> Target: 老
@enduml