@startuml

HotPizza --|> Pizza
ColdPizza --|> Pizza

HotMilk --|> Milk
ColdMilk --|> Milk

HotFoodFactory --|> Factory
ColdFoodFactory --|> Factory

'HotFoodFactory ..> HotMilk
'HotFoodFactory ..> HotPizza
'
'ColdFoodFactory ..> ColdMilk
'ColdFoodFactory ..> ColdPizza
@enduml