@startuml

class Implementor{
    +operate();
}

class Abstraction{
    -Implementor
    +doSomething()
}

concreteImplementorA ..|> Implementor
concreteImplementorB ..|> Implementor

Impl --> Abstraction
Abstraction o-- Implementor
@enduml