@startuml

    abstract class AbstractClass{
        +templateMethod();
        +primitiveOperation1();
        +primitiveOperation2();
    }

    class ConcreteClass{
        +primitiveOperation1();
        +primitiveOperation2();
    }
    ConcreteClass --|> AbstractClass

@enduml